let _data = {
    items: [{
        "restaurant": {
            "activities": [{
                "attribute": "{\"80\": {\"1\": 36.0, \"0\": 0}, \"25\": {\"1\": 22.0, \"0\": 0}, \"50\": {\"1\": 30.0, \"0\": 0}}",
                "description": "满25减22，满50减30，满80减36",
                "icon_color": "f07373",
                "icon_name": "减",
                "id": 1502340666,
                "is_exclusive_with_food_activity": true,
                "name": "大碗菜",
                "tips": "满25减22，满50减30，满80减36",
                "type": 102
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1364119297,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1364119305,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1364122225,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1364120033,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1364120041,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1364120049,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1364119313,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1364100353,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1364100289,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1364100249,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1364100209,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1364100305,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1364100217,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1364100321,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1364100345,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1364100225,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1364100257,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1364100313,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1364100361,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1364100329,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1364100265,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1364100337,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1364100241,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1364100297,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1163587081,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1163587097,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1163587113,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1163587145,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1059256505,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1163587169,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1059256433,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1059256441,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1163587201,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1059256481,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1163587185,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1163587049,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1059256465,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1163587033,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1163587025,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1059256449,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1163587193,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1163587009,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1059256417,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1059256425,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1163587121,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "9.9",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 372752210,
                "name": "9.9",
                "tips": "9.9"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1163587129,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1059256521,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1163587105,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1059256497,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1163587089,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1163587177,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1163587057,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1163587041,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1163587161,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1163587153,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "9.9",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 365076002,
                "name": "9.9",
                "tips": "9.9"
            }, {
                "description": "9.9",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 365073642,
                "name": "9.9",
                "tips": "9.9"
            }, {
                "description": "9.9",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 365071602,
                "name": "9.9",
                "tips": "9.9"
            }],
            "address": "深圳市宝安区西乡街道劳动社区劳动二队劳动路38号101铺",
            "authentic_id": 8383505623242024,
            "business_info": "{}",
            "description": "",
            "distance": 656,
            "favored": false,
            "flavors": [{"id": 221, "name": "川湘菜"}, {"id": 265, "name": "简餐"}],
            "float_delivery_fee": 1.5,
            "float_minimum_order_amount": 0,
            "has_story": false,
            "id": 1385324,
            "image_path": "c3201c23b932ec8b6199275f19351jpeg",
            "is_new": false,
            "is_premium": false,
            "is_stock_empty": 0,
            "is_valid": 1,
            "latitude": 22.568659,
            "longitude": 113.866225,
            "max_applied_quantity_per_order": -1,
            "name": "湖南大碗菜(西乡店)",
            "next_business_time": "",
            "only_use_poi": false,
            "opening_hours": ["09:05/21:50"],
            "order_lead_time": 31,
            "phone": "18207678943",
            "piecewise_agent_fee": {
                "description": "优惠配送费¥1.5",
                "extra_fee": -0.5,
                "is_extra": true,
                "no_subsidy_fee": "¥2.5",
                "rules": [{"fee": 1.5, "price": 0}],
                "tips": "优惠配送费¥1.5"
            },
            "platform": 0,
            "posters": [],
            "promotion_info": "本店菜都配米饭。除了写不含米饭。",
            "rating": 3.9,
            "rating_count": 390,
            "recent_order_num": 2725,
            "recommend": {
                "image_hash": "731111f3f9379e772eedf4855beae8a1jpeg",
                "is_ad": false,
                "track": "{\"rankType\":\"27\"}"
            },
            "recommend_reasons": [{"name": "配送飞快"}],
            "regular_customer_count": 0,
            "scheme": "eleme://catering?restaurant_id=1385324",
            "status": 1,
            "support_tags": [{
                "border": "dddddd",
                "color": "666666",
                "icon": "4e20966ca2a516de3f02fb9c7fd1bc6dpng",
                "text": "川湘菜",
                "type": 1
            }, {"border": "dddddd", "color": "333333", "text": "品质联盟"}],
            "supports": [{
                "border": "90dddddd",
                "description": "该商户食品安全已由国泰产险承担，食品安全有保障",
                "icon_color": "999999",
                "icon_name": "保",
                "id": 7,
                "name": "食安保",
                "text_color": "666666",
                "two_characters_icon_name": "保险"
            }],
            "tags": [],
            "theme": {
                "default_color": "2395ff",
                "header_style": 0,
                "hongbao_style": 0,
                "price_color": "ff5339",
                "third_tab_name": "商家",
                "vanish_fields": []
            },
            "type": 0
        }
    }, {
        "restaurant": {
            "activities": [{
                "attribute": "17.0",
                "description": "新用户下单立减17元",
                "icon_color": "70bc46",
                "icon_name": "首",
                "id": 800446682,
                "is_exclusive_with_food_activity": true,
                "name": "新用户立减(不与其他活动共享)",
                "tips": "新用户下单立减17元",
                "type": 103
            }, {
                "attribute": "{\"60\": {\"1\": 2.0, \"0\": 0}, \"30\": {\"1\": 1.0, \"0\": 0}}",
                "description": "满30减1，满60减2",
                "icon_color": "f07373",
                "icon_name": "减",
                "id": 1345318489,
                "is_exclusive_with_food_activity": true,
                "name": "自营销复杂满减活动",
                "tips": "满30减1，满60减2",
                "type": 102
            }],
            "address": "深圳市宝安区西乡街道鸣乐东街26号",
            "authentic_id": 6333585619080564,
            "business_info": "{}",
            "delivery_mode": {
                "border": "",
                "color": "2395FF",
                "gradient": {"rgb_from": "00AAFF", "rgb_to": "0085FF"},
                "icon_hash": "b9b45d2f6ff0dbeef3a78ef0e4e90abapng",
                "id": 1,
                "is_solid": true,
                "text": "蜂鸟专送",
                "text_color": "FFFFFF"
            },
            "description": "",
            "distance": 988,
            "favored": false,
            "flavors": [{"id": 263, "name": "其他菜系"}, {"id": 222, "name": "粤菜"}],
            "float_delivery_fee": 3,
            "float_minimum_order_amount": 20,
            "has_story": false,
            "id": 1873264,
            "image_path": "498f0100ef03d4707071cbbf9ad74png",
            "is_new": false,
            "is_premium": false,
            "is_stock_empty": 0,
            "is_valid": 1,
            "latitude": 22.572928,
            "longitude": 113.875763,
            "max_applied_quantity_per_order": -1,
            "name": "海陆丰家乡擂茶(西乡店)",
            "next_business_time": "明天10:20",
            "only_use_poi": false,
            "opening_hours": ["10:20/22:00"],
            "order_lead_time": 29,
            "phone": "13714121906",
            "piecewise_agent_fee": {
                "description": "配送费¥3",
                "extra_fee": 0,
                "is_extra": false,
                "no_subsidy_fee": "",
                "rules": [{"fee": 3, "price": 20}],
                "tips": "配送费¥3"
            },
            "platform": 0,
            "posters": [],
            "promotion_info": "百年传承、用心做好擂茶",
            "rating": 4.7,
            "rating_count": 165,
            "recent_order_num": 452,
            "recommend": {
                "color": "#e8470b",
                "image_hash": "",
                "is_ad": false,
                "reason": "",
                "track": "{\"rankType\":\"27\"}"
            },
            "recommend_reasons": [{"name": "配送飞快"}],
            "regular_customer_count": 0,
            "scheme": "eleme://catering?restaurant_id=1873264",
            "status": 1,
            "support_tags": [{
                "border": "dddddd",
                "color": "666666",
                "icon": "4e20966ca2a516de3f02fb9c7fd1bc6dpng",
                "text": "其他菜系",
                "type": 1
            }, {"border": "dddddd", "color": "666666", "text": "口碑人气好店"}, {
                "border": "dddddd",
                "color": "333333",
                "text": "品质联盟"
            }],
            "supports": [{
                "border": "90dddddd",
                "description": "该商户食品安全已由国泰产险承担，食品安全有保障",
                "icon_color": "999999",
                "icon_name": "保",
                "id": 7,
                "name": "食安保",
                "text_color": "666666",
                "two_characters_icon_name": "保险"
            }],
            "tags": [],
            "theme": {
                "default_color": "2395ff",
                "header_style": 0,
                "hongbao_style": 0,
                "price_color": "ff5339",
                "third_tab_name": "商家",
                "vanish_fields": []
            },
            "type": 0
        }
    }, {
        "restaurant": {
            "activities": [{
                "attribute": "17.0",
                "description": "新用户下单立减17元",
                "icon_color": "70bc46",
                "icon_name": "首",
                "id": 1499988265,
                "is_exclusive_with_food_activity": true,
                "name": "新用户立减(不与其他活动共享)",
                "tips": "新用户下单立减17元",
                "type": 103
            }, {
                "attribute": "{\"400\": {\"1\": 30.0, \"0\": 0}, \"70\": {\"1\": 20.0, \"0\": 0}, \"45\": {\"1\": 14.0, \"0\": 0}, \"22\": {\"1\": 9.0, \"0\": 0}}",
                "description": "满22减9，满45减14，满70减20，满400减30",
                "icon_color": "f07373",
                "icon_name": "减",
                "id": 1491000810,
                "is_exclusive_with_food_activity": true,
                "name": "manjian",
                "tips": "满22减9，满45减14，满70减20，满400减30",
                "type": 102
            }, {
                "description": "周大虾双人",
                "icon_color": "f07373",
                "icon_name": "折",
                "id": 1490490401,
                "name": "周大虾双人",
                "tips": "周大虾双人"
            }, {
                "description": "周大虾套餐2",
                "icon_color": "f07373",
                "icon_name": "折",
                "id": 1490482265,
                "name": "周大虾套餐2",
                "tips": "周大虾套餐2"
            }, {
                "description": "周大虾套餐2",
                "icon_color": "f07373",
                "icon_name": "折",
                "id": 1490483073,
                "name": "周大虾套餐2",
                "tips": "周大虾套餐2"
            }, {
                "description": "周大虾套餐1",
                "icon_color": "f07373",
                "icon_name": "折",
                "id": 1490474345,
                "name": "周大虾套餐1",
                "tips": "周大虾套餐1"
            }, {
                "description": "会员",
                "icon_color": "f07373",
                "icon_name": "折",
                "id": 1481785673,
                "name": "会员",
                "tips": "会员"
            }, {
                "description": "超值换购",
                "icon_color": "f1884f",
                "icon_name": "换",
                "id": 1474775529,
                "name": "超值换购",
                "tips": "超值换购"
            }, {
                "description": "超值换购",
                "icon_color": "f1884f",
                "icon_name": "换",
                "id": 1474764065,
                "name": "超值换购",
                "tips": "超值换购"
            }, {
                "description": "超值换购",
                "icon_color": "f1884f",
                "icon_name": "换",
                "id": 1474765025,
                "name": "超值换购",
                "tips": "超值换购"
            }],
            "address": "深圳市宝安区新安街道35区塘坊花园1巷1号",
            "authentic_id": 3393505608796126,
            "business_info": "{}",
            "description": "前方遥不可及 ，美食却只有一步之遥。当你埋头制作 PPT 时，小龙虾正爬出泥洞；当你看着枯燥的报表时，大师傅刚好往锅里洒了一把葱段；当你拥挤在公汽上时，镇江的料酒正冒出一丝香气；在你迷茫的时候，在你开心的时候，在你忙碌的时候，一份热辣的小龙虾会暖胃安心，让你感触生活的有滋有味。",
            "distance": 3848,
            "favored": false,
            "flavors": [{"id": 236, "name": "小龙虾"}, {"id": 265, "name": "简餐"}],
            "float_delivery_fee": 2.5,
            "float_minimum_order_amount": 20,
            "has_story": false,
            "id": 152159826,
            "image_path": "5ecfa00f25b9098402bd326ddf14fpng",
            "is_new": false,
            "is_premium": true,
            "is_stock_empty": 0,
            "is_valid": 1,
            "latitude": 22.578018,
            "longitude": 113.897048,
            "max_applied_quantity_per_order": -1,
            "name": "周大虾龙虾盖浇饭（新安街道二店）",
            "next_business_time": "明天09:30",
            "only_use_poi": false,
            "opening_hours": ["09:30/20:30"],
            "order_lead_time": 42,
            "phone": "021-60782942",
            "piecewise_agent_fee": {
                "description": "优惠配送费¥2.5",
                "extra_fee": -2,
                "is_extra": true,
                "no_subsidy_fee": "¥7",
                "rules": [{"fee": 2.5, "price": 20}],
                "tips": "优惠配送费¥2.5"
            },
            "platform": 0,
            "posters": [],
            "promotion_info": "",
            "rating": 4.7,
            "rating_count": 553,
            "recent_order_num": 1981,
            "recommend": {
                "image_hash": "731111f3f9379e772eedf4855beae8a1jpeg",
                "is_ad": false,
                "track": "{\"rankType\":\"5\"}"
            },
            "recommend_reasons": [{"name": "回头客多"}],
            "regular_customer_count": 0,
            "scheme": "eleme://catering?restaurant_id=152159826",
            "status": 1,
            "support_tags": [{
                "border": "dddddd",
                "color": "666666",
                "icon": "4e20966ca2a516de3f02fb9c7fd1bc6dpng",
                "text": "小龙虾",
                "type": 1
            }],
            "supports": [{
                "border": "90dddddd",
                "description": "该商家支持开发票，开票订单金额1元起，请在下单时填写好发票抬头",
                "icon_color": "999999",
                "icon_name": "票",
                "id": 4,
                "name": "开发票",
                "text_color": "666666",
                "two_characters_icon_name": "发票"
            }],
            "tags": [],
            "theme": {
                "default_color": "2395ff",
                "header_style": 0,
                "hongbao_style": 0,
                "price_color": "ff5339",
                "third_tab_name": "商家",
                "vanish_fields": []
            },
            "type": 0
        }
    }, {
        "restaurant": {
            "activities": [{
                "attribute": "17.0",
                "description": "新用户下单立减17元",
                "icon_color": "70bc46",
                "icon_name": "首",
                "id": 1392231041,
                "is_exclusive_with_food_activity": true,
                "name": "新用户立减(不与其他活动共享)",
                "tips": "新用户下单立减17元",
                "type": 103
            }, {
                "attribute": "{\"40\": {\"1\": 15.0, \"0\": 0}, \"100\": {\"1\": 35.0, \"0\": 0}, \"20\": {\"1\": 12.0, \"0\": 0}, \"200\": {\"1\": 70.0, \"0\": 0}, \"70\": {\"1\": 25.0, \"0\": 0}}",
                "description": "满20减12，满40减15，满70减25，满100减35，满200减70",
                "icon_color": "f07373",
                "icon_name": "减",
                "id": 1470210385,
                "is_exclusive_with_food_activity": true,
                "name": "自营销复杂满减活动",
                "tips": "满20减12，满40减15，满70减25，满100减35，满200减70",
                "type": 102
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1470207857,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1429556673,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1393687337,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "超值换购",
                "icon_color": "f1884f",
                "icon_name": "换",
                "id": 1388079529,
                "name": "超值换购",
                "tips": "超值换购"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1387301345,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1387298105,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1387297553,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1387296833,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1387294785,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1387293961,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1387290873,
                "name": "单品定价",
                "tips": "单品定价"
            }],
            "address": "深圳市宝安区西乡街道麻布社区轻铁西十五巷9号103铺",
            "authentic_id": 6393535611854608,
            "bidding": "{\"core\":{\"index\":3,\"extraInfo\":\"{\\\"bidding\\\":\\\"{161165390:161}\\\",\\\"rankId\\\":\\\"b714802b051849488445b10393d0f2f5\\\",\\\"rankTime\\\":\\\"1536900120\\\",\\\"cityId\\\":\\\"11\\\"}\",\"target\":{\"restaurantId\":165997308,\"weight\":200,\"probability\":0.26723000407218933},\"come_from\":0,\"next\":{\"restaurantId\":163214472,\"weight\":220,\"probability\":0.16126999258995056}}}",
            "business_info": "{}",
            "description": "",
            "distance": 370,
            "favored": false,
            "flavors": [{"id": 267, "name": "黄焖鸡米饭"}],
            "float_delivery_fee": 0,
            "float_minimum_order_amount": 0,
            "has_story": false,
            "id": 165997308,
            "image_path": "d9387673ce0d4fd14d973f0df43edjpeg",
            "is_new": false,
            "is_premium": false,
            "is_stock_empty": 0,
            "is_valid": 1,
            "latitude": 22.569908,
            "longitude": 113.86781,
            "max_applied_quantity_per_order": -1,
            "name": "正宗奇味黄焖鸡米饭(旗舰店)",
            "next_business_time": "",
            "only_use_poi": false,
            "opening_hours": ["10:00/22:30"],
            "order_lead_time": 43,
            "phone": "15915307313",
            "piecewise_agent_fee": {
                "description": "优惠免配送费",
                "extra_fee": -1,
                "is_extra": true,
                "no_subsidy_fee": "¥2",
                "rules": [{"fee": 0, "price": 0}],
                "tips": "优惠免配送费"
            },
            "platform": 0,
            "posters": [],
            "promotion_info": "",
            "rating": 4.4,
            "rating_count": 806,
            "recent_order_num": 3280,
            "recommend": {
                "image_hash": "731111f3f9379e772eedf4855beae8a1jpeg",
                "is_ad": true,
                "reason": "广告",
                "track": "{\"rankType\":\"8\"}"
            },
            "recommend_reasons": [],
            "regular_customer_count": 0,
            "scheme": "eleme://catering?restaurant_id=165997308",
            "status": 1,
            "support_tags": [{
                "border": "dddddd",
                "color": "666666",
                "icon": "4e20966ca2a516de3f02fb9c7fd1bc6dpng",
                "text": "黄焖鸡米饭",
                "type": 1
            }],
            "supports": [{
                "border": "90dddddd",
                "description": "该商户食品安全已由国泰产险承担，食品安全有保障",
                "icon_color": "999999",
                "icon_name": "保",
                "id": 7,
                "name": "食安保",
                "text_color": "666666",
                "two_characters_icon_name": "保险"
            }],
            "theme": {
                "default_color": "2395ff",
                "header_style": 0,
                "hongbao_style": 0,
                "price_color": "ff5339",
                "third_tab_name": "商家",
                "vanish_fields": []
            },
            "type": 0
        }
    }, {
        "restaurant": {
            "activities": [{
                "attribute": "17.0",
                "description": "新用户下单立减17元",
                "icon_color": "70bc46",
                "icon_name": "首",
                "id": 1267217673,
                "is_exclusive_with_food_activity": true,
                "name": "新用户立减(不与其他活动共享)",
                "tips": "新用户下单立减17元",
                "type": 103
            }, {
                "attribute": "{\"60\": {\"1\": 18.0, \"0\": 0}, \"35\": {\"1\": 12.0, \"0\": 0}, \"20\": {\"1\": 8.0, \"0\": 0}, \"100\": {\"1\": 30.0, \"0\": 0}}",
                "description": "满20减8，满35减12，满60减18，满100减30",
                "icon_color": "f07373",
                "icon_name": "减",
                "id": 1515858353,
                "is_exclusive_with_food_activity": false,
                "name": "自营销复杂满减活动",
                "tips": "满20减8，满35减12，满60减18，满100减30",
                "type": 102
            }, {
                "description": "单品折扣",
                "icon_color": "f07373",
                "icon_name": "折",
                "id": 1487414129,
                "name": "单品折扣",
                "tips": "单品折扣"
            }, {
                "description": "单品折扣",
                "icon_color": "f07373",
                "icon_name": "折",
                "id": 1487412521,
                "name": "单品折扣",
                "tips": "单品折扣"
            }, {
                "description": "单品折扣",
                "icon_color": "f07373",
                "icon_name": "折",
                "id": 1486889409,
                "name": "单品折扣",
                "tips": "单品折扣"
            }, {
                "description": "单品折扣",
                "icon_color": "f07373",
                "icon_name": "折",
                "id": 1486883681,
                "name": "单品折扣",
                "tips": "单品折扣"
            }, {
                "attribute": "{\"55.0\": {\"quantity\": 1, \"must_pay_online\": 1, \"name\": \"\\u53ef\\u4e50\"}}",
                "description": "满55元赠送可乐1份",
                "icon_color": "3cc791",
                "icon_name": "赠",
                "id": 515827817,
                "is_exclusive_with_food_activity": true,
                "name": "自营销赠品活动",
                "tips": "满55元赠送可乐1份",
                "type": 106
            }],
            "address": "深圳市宝安区西乡街道共乐社区高树围西二巷11号104",
            "authentic_id": 4353545622228472,
            "bidding": "{\"core\":{\"index\":4,\"extraInfo\":\"{\\\"bidding\\\":\\\"{161165390:161}\\\",\\\"rankId\\\":\\\"b714802b051849488445b10393d0f2f5\\\",\\\"rankTime\\\":\\\"1536900120\\\",\\\"cityId\\\":\\\"11\\\"}\",\"target\":{\"restaurantId\":163214472,\"weight\":220,\"probability\":0.16126999258995056},\"come_from\":0,\"next\":{\"restaurantId\":162491001,\"weight\":160,\"probability\":0.180649995803833}}}",
            "business_info": "{}",
            "description": "",
            "distance": 1288,
            "favored": false,
            "flavors": [{"id": 267, "name": "黄焖鸡米饭"}, {"id": 269, "name": "煲仔饭"}],
            "float_delivery_fee": 2,
            "float_minimum_order_amount": 0,
            "has_story": false,
            "id": 163214472,
            "image_path": "99710e0585b282e37d01bdb7ac755jpeg",
            "is_new": false,
            "is_premium": false,
            "is_stock_empty": 0,
            "is_valid": 1,
            "latitude": 22.579237,
            "longitude": 113.864528,
            "max_applied_quantity_per_order": -1,
            "name": "康记黄焖鸡米饭(西乡店)",
            "next_business_time": "明天10:00",
            "only_use_poi": false,
            "opening_hours": ["10:00/24:00"],
            "order_lead_time": 27,
            "phone": "13510673019",
            "piecewise_agent_fee": {
                "description": "配送费¥2",
                "extra_fee": 0,
                "is_extra": false,
                "no_subsidy_fee": "",
                "rules": [{"fee": 2, "price": 0}],
                "tips": "配送费¥2"
            },
            "platform": 0,
            "posters": [],
            "promotion_info": "亲，好吃请收藏店铺，本店尽心为你服务",
            "rating": 4.6,
            "rating_count": 158,
            "recent_order_num": 615,
            "recommend": {
                "image_hash": "731111f3f9379e772eedf4855beae8a1jpeg",
                "is_ad": true,
                "reason": "广告",
                "track": "{\"rankType\":\"8\"}"
            },
            "recommend_reasons": [{"name": "配送飞快"}],
            "regular_customer_count": 0,
            "scheme": "eleme://catering?restaurant_id=163214472",
            "status": 1,
            "support_tags": [{
                "border": "dddddd",
                "color": "666666",
                "icon": "4e20966ca2a516de3f02fb9c7fd1bc6dpng",
                "text": "黄焖鸡米饭",
                "type": 1
            }],
            "supports": [{
                "border": "90dddddd",
                "description": "该商户食品安全已由国泰产险承担，食品安全有保障",
                "icon_color": "999999",
                "icon_name": "保",
                "id": 7,
                "name": "食安保",
                "text_color": "666666",
                "two_characters_icon_name": "保险"
            }],
            "theme": {
                "default_color": "2395ff",
                "header_style": 0,
                "hongbao_style": 0,
                "price_color": "ff5339",
                "third_tab_name": "商家",
                "vanish_fields": []
            },
            "type": 0
        }
    }, {
        "restaurant": {
            "activities": [{
                "attribute": "17.0",
                "description": "新用户下单立减17元",
                "icon_color": "70bc46",
                "icon_name": "首",
                "id": 803333282,
                "is_exclusive_with_food_activity": true,
                "name": "新用户立减(不与其他活动共享)",
                "tips": "新用户下单立减17元",
                "type": 103
            }, {
                "attribute": "{\"40\": {\"1\": 14.0, \"0\": 0}, \"68\": {\"1\": 16.0, \"0\": 0}, \"28\": {\"1\": 12.0, \"0\": 0}}",
                "description": "满28减12，满40减14，满68减16",
                "icon_color": "f07373",
                "icon_name": "减",
                "id": 1520187682,
                "is_exclusive_with_food_activity": true,
                "name": "正新",
                "tips": "满28减12，满40减14，满68减16",
                "type": 102
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1526517705,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1524482209,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1507311225,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1489039849,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1489039841,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1444189697,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1386900729,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1386894769,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1386892521,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1386892505,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1383116609,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1383116617,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1383116657,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1383116649,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1383116633,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1383116577,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1383116593,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1383116585,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1317767657,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1317767649,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1317766377,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1134139113,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1084932473,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1084932449,
                "name": "单品定价",
                "tips": "单品定价"
            }],
            "address": "深圳市宝安区西乡街道新湖路139号",
            "authentic_id": 7393505608642877,
            "business_info": "{}",
            "delivery_mode": {
                "border": "",
                "color": "2395FF",
                "gradient": {"rgb_from": "00AAFF", "rgb_to": "0085FF"},
                "icon_hash": "b9b45d2f6ff0dbeef3a78ef0e4e90abapng",
                "id": 1,
                "is_solid": true,
                "text": "蜂鸟专送",
                "text_color": "FFFFFF"
            },
            "description": "",
            "distance": 340,
            "favored": false,
            "flavors": [{"id": 234, "name": "炸鸡炸串"}, {"id": 212, "name": "汉堡"}],
            "float_delivery_fee": 0,
            "float_minimum_order_amount": 20,
            "folding_restaurant_brand": "正新鸡排",
            "folding_restaurants": [{
                "distance": 688,
                "id": 160204488,
                "name": "正新鸡排(西乡天虹店)",
                "order_lead_time": 31,
                "scheme": "eleme://catering?restaurant_id=160204488",
                "type": 0
            }],
            "has_story": false,
            "id": 1997877,
            "image_path": "a93fd92d242a7352e9fdb64b7d2eapng",
            "is_new": false,
            "is_premium": true,
            "is_stock_empty": 0,
            "is_valid": 1,
            "latitude": 22.569878,
            "longitude": 113.869295,
            "max_applied_quantity_per_order": -1,
            "name": "正新鸡排（坪洲店）",
            "next_business_time": "",
            "only_use_poi": false,
            "opening_hours": ["10:00/01:30"],
            "order_lead_time": 20,
            "phone": "13714278189",
            "piecewise_agent_fee": {
                "description": "优惠免配送费",
                "extra_fee": -1.5,
                "is_extra": true,
                "no_subsidy_fee": "¥3",
                "rules": [{"fee": 0, "price": 20}],
                "tips": "优惠免配送费"
            },
            "platform": 0,
            "posters": [],
            "promotion_info": "",
            "rating": 4.8,
            "rating_count": 1595,
            "recent_order_num": 1975,
            "recommend": {
                "image_hash": "731111f3f9379e772eedf4855beae8a1jpeg",
                "is_ad": false,
                "track": "{\"rankType\":\"17\",\"trafficCardId\":\"47758745\"}"
            },
            "recommend_reasons": [{"name": "回头客多"}, {"name": "配送飞快"}],
            "regular_customer_count": 0,
            "scheme": "eleme://catering?restaurant_id=1997877",
            "status": 1,
            "support_tags": [{
                "border": "dddddd",
                "color": "666666",
                "icon": "4e20966ca2a516de3f02fb9c7fd1bc6dpng",
                "text": "炸鸡炸串",
                "type": 1
            }],
            "supports": [],
            "theme": {
                "default_color": "2395ff",
                "header_style": 0,
                "hongbao_style": 0,
                "price_color": "ff5339",
                "third_tab_name": "商家",
                "vanish_fields": []
            },
            "type": 0
        }
    }, {
        "restaurant": {
            "activities": [{
                "attribute": "25.0",
                "description": "新用户下单立减25元",
                "icon_color": "70bc46",
                "icon_name": "首",
                "id": 1522566145,
                "is_exclusive_with_food_activity": true,
                "name": "新客立减25",
                "tips": "新用户下单立减25元",
                "type": 103
            }, {
                "attribute": "{\"100\": {\"1\": 50.0, \"0\": 0}}",
                "description": "满100减50",
                "icon_color": "f07373",
                "icon_name": "减",
                "id": 1532132410,
                "is_exclusive_with_food_activity": true,
                "name": "必胜客",
                "tips": "满100减50",
                "type": 102
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1532282641,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价(限10:00-17:00)",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1519041458,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价(限10:00-17:00)",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1519028530,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价(限10:00-17:00)",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1519016370,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价(限10:00-17:00)",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1519009114,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价(限10:00-17:00)",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1518991914,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价(限10:00-17:00)",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1518969754,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1513819449,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1513635537,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1497059617,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1497059577,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1497053569,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "超值换购",
                "icon_color": "f1884f",
                "icon_name": "换",
                "id": 1496253665,
                "name": "超值换购",
                "tips": "超值换购"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1481546489,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1481532353,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1481511185,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1481511385,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1481428537,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1481428153,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1481428913,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1481416113,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1481415625,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1481402497,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1481396033,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1481393201,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1481389297,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1481383449,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1451956817,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1451909041,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1451901753,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1451897209,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1451860121,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1451460585,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1451450553,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "单品定价",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1451075657,
                "name": "单品定价",
                "tips": "单品定价"
            }, {
                "description": "59",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1365067361,
                "name": "59",
                "tips": "59"
            }, {
                "description": "59",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1365068273,
                "name": "59",
                "tips": "59"
            }, {
                "description": "饿了么",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1338332977,
                "name": "饿了么",
                "tips": "饿了么"
            }, {
                "description": "超值至尊比萨套餐/匈牙利",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1338314033,
                "name": "超值至尊比萨套餐/匈牙利",
                "tips": "超值至尊比萨套餐/匈牙利"
            }, {
                "description": "广深佛厦",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1332996033,
                "name": "广深佛厦",
                "tips": "广深佛厦"
            }, {
                "description": "照烧鸡肉炒饭套餐",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1332703073,
                "name": "照烧鸡肉炒饭套餐",
                "tips": "照烧鸡肉炒饭套餐"
            }, {
                "description": "榴莲多多芝心比萨2人餐",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1332534217,
                "name": "榴莲多多芝心比萨2人餐",
                "tips": "榴莲多多芝心比萨2人餐"
            }, {
                "description": "榴莲多多薄底比萨2人餐",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 1332518633,
                "name": "榴莲多多薄底比萨2人餐",
                "tips": "榴莲多多薄底比萨2人餐"
            }],
            "address": "深圳市宝安区西乡街道劳动社区兴业路与悦和路交汇处劳动综合楼一楼A9",
            "authentic_id": 3353555602858707,
            "business_info": "{}",
            "delivery_mode": {
                "border": "",
                "color": "2395FF",
                "gradient": {"rgb_from": "00AAFF", "rgb_to": "0085FF"},
                "icon_hash": "b9b45d2f6ff0dbeef3a78ef0e4e90abapng",
                "id": 1,
                "is_solid": true,
                "text": "蜂鸟专送",
                "text_color": "FFFFFF"
            },
            "description": " 必胜客（兴业店）",
            "distance": 1812,
            "favored": false,
            "flavors": [{"id": 211, "name": "披萨意面"}, {"id": 265, "name": "简餐"}],
            "float_delivery_fee": 2.5,
            "float_minimum_order_amount": 20,
            "folding_restaurant_brand": "必胜客",
            "folding_restaurants": [{
                "distance": 2430,
                "id": 464320,
                "name": "必胜客宅急送(新湖店)",
                "order_lead_time": 43,
                "scheme": "eleme://catering?restaurant_id=464320",
                "type": 0
            }],
            "has_story": false,
            "id": 464507,
            "image_path": "3c54d8b5a9b582555bc9e97430acfpng",
            "is_new": false,
            "is_premium": true,
            "is_stock_empty": 0,
            "is_valid": 1,
            "latitude": 22.568796,
            "longitude": 113.856842,
            "max_applied_quantity_per_order": -1,
            "name": "必胜客宅急送(兴业店)",
            "next_business_time": "明天10:30",
            "only_use_poi": false,
            "opening_hours": ["10:30/22:30"],
            "order_lead_time": 43,
            "phone": "0755-23728691",
            "piecewise_agent_fee": {
                "description": "优惠配送费¥2.5",
                "extra_fee": -2.5,
                "is_extra": true,
                "no_subsidy_fee": "¥5",
                "rules": [{"fee": 2.5, "price": 20}],
                "tips": "优惠配送费¥2.5"
            },
            "platform": 0,
            "posters": [],
            "promotion_info": "配送费现从9元优惠至5元,该优惠将在小票的本单优惠金额中立减。用餐高峰时间可能会延长送餐时间，请以实际送餐时间为准。如果需要Fapiao请在订单备注Fapiao,我们将为您提供电子Fapiao提取码。比萨尺寸为英寸,指烤盘的直径,仅供参考,实际规格请以克重为准。",
            "rating": 4.6,
            "rating_count": 525,
            "recent_order_num": 649,
            "recommend": {
                "image_hash": "731111f3f9379e772eedf4855beae8a1jpeg",
                "is_ad": false,
                "track": "{\"rankType\":\"3\"}"
            },
            "recommend_reasons": [],
            "regular_customer_count": 0,
            "scheme": "eleme://catering?restaurant_id=464507",
            "status": 1,
            "support_tags": [{
                "border": "dddddd",
                "color": "666666",
                "icon": "4e20966ca2a516de3f02fb9c7fd1bc6dpng",
                "text": "披萨意面",
                "type": 1
            }],
            "supports": [{
                "border": "90dddddd",
                "description": "该商家支持开发票，请在下单时填写好发票抬头",
                "icon_color": "999999",
                "icon_name": "票",
                "id": 4,
                "name": "开发票",
                "text_color": "666666",
                "two_characters_icon_name": "发票"
            }],
            "tags": [],
            "theme": {
                "default_color": "2395ff",
                "header_style": 0,
                "hongbao_style": 0,
                "price_color": "ff5339",
                "third_tab_name": "商家",
                "vanish_fields": []
            },
            "type": 0
        }
    }, {
        "restaurant": {
            "activities": [{
                "attribute": "17.0",
                "description": "新用户下单立减17元",
                "icon_color": "70bc46",
                "icon_name": "首",
                "id": 1500037457,
                "is_exclusive_with_food_activity": true,
                "name": "新用户立减(不与其他活动共享)",
                "tips": "新用户下单立减17元",
                "type": 103
            }, {
                "attribute": "{\"75\": {\"1\": 40.0, \"0\": 0}, \"60\": {\"1\": 30.0, \"0\": 0}, \"29\": {\"1\": 17.0, \"0\": 0}, \"45\": {\"1\": 22.0, \"0\": 0}}",
                "description": "满29减17，满45减22，满60减30，满75减40",
                "icon_color": "f07373",
                "icon_name": "减",
                "id": 1491001506,
                "is_exclusive_with_food_activity": true,
                "name": "manjian",
                "tips": "满29减17，满45减22，满60减30，满75减40",
                "type": 102
            }, {
                "description": "超值换购",
                "icon_color": "f1884f",
                "icon_name": "换",
                "id": 1522641458,
                "name": "超值换购",
                "tips": "超值换购"
            }, {
                "description": "常规活动",
                "icon_color": "f07373",
                "icon_name": "折",
                "id": 1462895289,
                "name": "常规活动",
                "tips": "常规活动"
            }, {
                "description": "常规活动",
                "icon_color": "f07373",
                "icon_name": "折",
                "id": 525347777,
                "name": "常规活动",
                "tips": "常规活动"
            }, {
                "description": "玉米排骨汤+台式卤肉饭",
                "icon_color": "f1884f",
                "icon_name": "特",
                "id": 521973297,
                "name": "玉米排骨汤+台式卤肉饭",
                "tips": "玉米排骨汤+台式卤肉饭"
            }],
            "address": "深圳市宝安区新安街道35区塘坊花园1巷1号",
            "authentic_id": 7393525623700908,
            "business_info": "{}",
            "description": "小马哥金牌卤肉饭源自台湾配方，选用上等带膘五花肉经过5小时慢火熬制。我们把特色和地道的台湾味道呈现在您的面前，希望在快节奏的都市生活通过我们的食品能让您感受到一份来自宝岛的浓浓情意和问候。",
            "distance": 3678,
            "favored": false,
            "flavors": [{"id": 265, "name": "简餐"}, {"id": 237, "name": "地方小吃"}],
            "float_delivery_fee": 5.5,
            "float_minimum_order_amount": 20,
            "has_story": false,
            "id": 156056408,
            "image_path": "0de3840d3b9b45e8da0795e7179ecpng",
            "is_new": false,
            "is_premium": true,
            "is_stock_empty": 0,
            "is_valid": 1,
            "latitude": 22.577629,
            "longitude": 113.895842,
            "max_applied_quantity_per_order": -1,
            "name": "小马哥卤肉饭(新安街道二店)",
            "next_business_time": "明天09:30",
            "only_use_poi": false,
            "opening_hours": ["09:30/20:30"],
            "order_lead_time": 41,
            "phone": "021-60782942",
            "piecewise_agent_fee": {
                "description": "优惠配送费¥5.5",
                "extra_fee": 1,
                "is_extra": true,
                "no_subsidy_fee": "¥7",
                "rules": [{"fee": 5.5, "price": 20}],
                "tips": "优惠配送费¥5.5"
            },
            "platform": 0,
            "posters": [],
            "promotion_info": "欢迎进入“小马哥卤肉饭”。订餐须知：为了确保能及时用餐，希望您提前45分钟以上预定下单，避开高峰时期。",
            "rating": 4.5,
            "rating_count": 546,
            "recent_order_num": 2097,
            "recommend": {
                "image_hash": "731111f3f9379e772eedf4855beae8a1jpeg",
                "is_ad": false,
                "track": "{\"rankType\":\"5\"}"
            },
            "recommend_reasons": [{"name": "味道超赞"}],
            "regular_customer_count": 0,
            "scheme": "eleme://catering?restaurant_id=156056408",
            "status": 1,
            "support_tags": [{
                "border": "dddddd",
                "color": "666666",
                "icon": "4e20966ca2a516de3f02fb9c7fd1bc6dpng",
                "text": "简餐",
                "type": 1
            }],
            "supports": [{
                "border": "90dddddd",
                "description": "该商家支持开发票，开票订单金额1元起，请在下单时填写好发票抬头",
                "icon_color": "999999",
                "icon_name": "票",
                "id": 4,
                "name": "开发票",
                "text_color": "666666",
                "two_characters_icon_name": "发票"
            }],
            "tags": [],
            "theme": {
                "default_color": "2395ff",
                "header_style": 0,
                "hongbao_style": 0,
                "price_color": "ff5339",
                "third_tab_name": "商家",
                "vanish_fields": []
            },
            "type": 0
        }
    }]
}

const fomrData = (baseurl = "http://wagnxx.net.cn/react/images/elm_img/") => _data.items.map((item, ind) => {
    let distObj = item.restaurant;
    return {
        src: baseurl + distObj.image_path + ".webp",
        shopName: distObj.name,
        star: distObj.rating,
        s: distObj.longitude,
        t: distObj.order_lead_time,
        ser_pr: distObj.piecewise_agent_fee.no_subsidy_fee,
        count: distObj["recent_order_num"]
    };
});

export default fomrData